# .github/workflows/build.yml

name: Build Windows Executable

on:
  push:
    branches:
      - main  # Você pode alterar para a branch desejada
  workflow_dispatch:  # Permite executar manualmente

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile ^
                      --add-data "excel_comparator\\app.py;." ^
                      excel_comparator/cli.py ^
                      --name ExcelComparator

      - name: Zip Executable
        run: |
          Compress-Archive -Path dist\\ExcelComparator.exe -DestinationPath ExcelComparator.zip

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExcelComparator-Windows
          path: dist/ExcelComparator.exe

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExcelComparator-Windows-Zip
          path: ExcelComparator.zip
