name: Build Windows Executable

on: [push]  # Roda o workflow a cada push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Use a versão necessária

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --add-data "excel_comparator\\app.py;." excel_comparator/cli.py --name ExcelComparator

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExcelComparator-Windows
          path: dist/ExcelComparator.exe
